const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "MNT");

  // 1. Identity Registry
  console.log("\n[1/3] Deploying VeritasIdentityRegistry...");
  const Identity = await hre.ethers.getContractFactory("VeritasIdentityRegistry");
  const identity = await Identity.deploy();
  await identity.waitForDeployment();
  const identityAddr = await identity.getAddress();
  console.log("✓ IdentityRegistry:", identityAddr);

  // 2. Reputation Registry
  console.log("\n[2/3] Deploying VeritasReputationRegistry...");
  const Reputation = await hre.ethers.getContractFactory("VeritasReputationRegistry");
  const reputation = await Reputation.deploy(identityAddr);
  await reputation.waitForDeployment();
  const reputationAddr = await reputation.getAddress();
  console.log("✓ ReputationRegistry:", reputationAddr);

  // 3. Validation Registry
  console.log("\n[3/3] Deploying VeritasValidationRegistry...");
  const Validation = await hre.ethers.getContractFactory("VeritasValidationRegistry");
  const validation = await Validation.deploy(reputationAddr);
  await validation.waitForDeployment();
  const validationAddr = await validation.getAddress();
  console.log("✓ ValidationRegistry:", validationAddr);

  // Register 3 agents
  console.log("\n[4] Registering VERITAS agents...");
  const agents = ["VERITAS-01", "VERITAS-02", "VERITAS-03"];
  for (const name of agents) {
    const metaHash = hre.ethers.keccak256(hre.ethers.toUtf8Bytes(name + "_meta_v1"));
    const tx = await identity.registerAgent(name, metaHash);
    await tx.wait();
    console.log("✓ Registered:", name);
  }

  // Add validation contract as validator on reputation
  const tx1 = await reputation.addValidator(validationAddr);
  await tx1.wait();
  console.log("✓ ValidationRegistry added as reputation validator");

  // Write addresses to root .env and to frontend
  const envPath   = path.join(__dirname, "../../.env");
  const envLines  = [
    `IDENTITY_REGISTRY=${identityAddr}`,
    `REPUTATION_REGISTRY=${reputationAddr}`,
    `VALIDATION_REGISTRY=${validationAddr}`,
    `VITE_IDENTITY_REGISTRY=${identityAddr}`,
    `VITE_REPUTATION_REGISTRY=${reputationAddr}`,
    `VITE_VALIDATION_REGISTRY=${validationAddr}`,
  ];

  // Append to existing .env (don't overwrite keys)
  let existing = "";
  try { existing = fs.readFileSync(envPath, "utf8"); } catch {}
  const updated = existing + "\n" + envLines.join("\n") + "\n";
  fs.writeFileSync(envPath, updated);
  console.log("\n✓ Contract addresses written to .env");

  // Write ABI addresses to frontend/src/lib/addresses.js
  const addrFile = path.join(__dirname, "../../frontend/src/lib/addresses.js");
  fs.writeFileSync(addrFile, `// Auto-generated by deploy.js
export const IDENTITY_REGISTRY   = "${identityAddr}";
export const REPUTATION_REGISTRY = "${reputationAddr}";
export const VALIDATION_REGISTRY = "${validationAddr}";
export const MANTLE_CHAIN_ID     = ${hre.network.config.chainId};
`);
  console.log("✓ Addresses written to frontend/src/lib/addresses.js");

  console.log("\n══════════════════════════════════════");
  console.log("DEPLOYMENT COMPLETE");
  console.log("Identity:   ", identityAddr);
  console.log("Reputation: ", reputationAddr);
  console.log("Validation: ", validationAddr);
  console.log("══════════════════════════════════════");
  console.log("\nNext: npx hardhat verify --network mantle_testnet", identityAddr);
  console.log("Next: npx hardhat verify --network mantle_testnet", reputationAddr, `"${identityAddr}"`);
  console.log("Next: npx hardhat verify --network mantle_testnet", validationAddr, `"${reputationAddr}"`);
}

main().catch((e) => { console.error(e); process.exit(1); });